// Mocks generated by Mockito 5.4.4 from annotations
// in rick_morty/test/app/data_layer/repositories/home_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:rick_morty/app/data_layer/data_layer.dart' as _i3;
import 'package:rick_morty/app/domain_layer/domain_layer.dart' as _i4;
import 'package:rick_morty/app/infra/infra.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIHttpClient_0 extends _i1.SmartFake implements _i2.IHttpClient {
  _FakeIHttpClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeListDTO_1 extends _i1.SmartFake implements _i3.HomeListDTO {
  _FakeHomeListDTO_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeCharacterDTO_2 extends _i1.SmartFake
    implements _i3.HomeCharacterDTO {
  _FakeHomeCharacterDTO_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeInfoEntity_3 extends _i1.SmartFake
    implements _i4.HomeInfoEntity {
  _FakeHomeInfoEntity_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataSource extends _i1.Mock implements _i3.HomeDataSource {
  @override
  _i2.IHttpClient get http => (super.noSuchMethod(
        Invocation.getter(#http),
        returnValue: _FakeIHttpClient_0(
          this,
          Invocation.getter(#http),
        ),
        returnValueForMissingStub: _FakeIHttpClient_0(
          this,
          Invocation.getter(#http),
        ),
      ) as _i2.IHttpClient);

  @override
  _i5.Future<_i3.HomeListDTO> getCharacters({
    required int? page,
    String? name,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [],
          {
            #page: page,
            #name: name,
            #status: status,
          },
        ),
        returnValue: _i5.Future<_i3.HomeListDTO>.value(_FakeHomeListDTO_1(
          this,
          Invocation.method(
            #getCharacters,
            [],
            {
              #page: page,
              #name: name,
              #status: status,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.HomeListDTO>.value(_FakeHomeListDTO_1(
          this,
          Invocation.method(
            #getCharacters,
            [],
            {
              #page: page,
              #name: name,
              #status: status,
            },
          ),
        )),
      ) as _i5.Future<_i3.HomeListDTO>);

  @override
  _i5.Future<_i3.HomeCharacterDTO> getCharacterById({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterById,
          [],
          {#id: id},
        ),
        returnValue:
            _i5.Future<_i3.HomeCharacterDTO>.value(_FakeHomeCharacterDTO_2(
          this,
          Invocation.method(
            #getCharacterById,
            [],
            {#id: id},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.HomeCharacterDTO>.value(_FakeHomeCharacterDTO_2(
          this,
          Invocation.method(
            #getCharacterById,
            [],
            {#id: id},
          ),
        )),
      ) as _i5.Future<_i3.HomeCharacterDTO>);
}

/// A class which mocks [HomeListDTO].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeListDTO extends _i1.Mock implements _i3.HomeListDTO {
  @override
  _i4.HomeInfoEntity get info => (super.noSuchMethod(
        Invocation.getter(#info),
        returnValue: _FakeHomeInfoEntity_3(
          this,
          Invocation.getter(#info),
        ),
        returnValueForMissingStub: _FakeHomeInfoEntity_3(
          this,
          Invocation.getter(#info),
        ),
      ) as _i4.HomeInfoEntity);

  @override
  List<_i4.HomeCharacterEntity> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: <_i4.HomeCharacterEntity>[],
        returnValueForMissingStub: <_i4.HomeCharacterEntity>[],
      ) as List<_i4.HomeCharacterEntity>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [HomeCharacterDTO].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeCharacterDTO extends _i1.Mock implements _i3.HomeCharacterDTO {
  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#status),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#status),
        ),
      ) as String);

  @override
  String get species => (super.noSuchMethod(
        Invocation.getter(#species),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#species),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#species),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  String get gender => (super.noSuchMethod(
        Invocation.getter(#gender),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#gender),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#gender),
        ),
      ) as String);

  @override
  String get originName => (super.noSuchMethod(
        Invocation.getter(#originName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#originName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#originName),
        ),
      ) as String);

  @override
  String get originUrl => (super.noSuchMethod(
        Invocation.getter(#originUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#originUrl),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#originUrl),
        ),
      ) as String);

  @override
  String get locationName => (super.noSuchMethod(
        Invocation.getter(#locationName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#locationName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#locationName),
        ),
      ) as String);

  @override
  String get locationUrl => (super.noSuchMethod(
        Invocation.getter(#locationUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#locationUrl),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#locationUrl),
        ),
      ) as String);

  @override
  String get image => (super.noSuchMethod(
        Invocation.getter(#image),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#image),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#image),
        ),
      ) as String);

  @override
  List<String> get episode => (super.noSuchMethod(
        Invocation.getter(#episode),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
