// Mocks generated by Mockito 5.4.4 from annotations
// in rick_morty/test/app/domain_layer/use_cases/get_home_character_by_id_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:rick_morty/app/domain_layer/domain_layer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeListEntity_0 extends _i1.SmartFake
    implements _i2.HomeListEntity {
  _FakeHomeListEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeCharacterEntity_1 extends _i1.SmartFake
    implements _i2.HomeCharacterEntity {
  _FakeHomeCharacterEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IHomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHomeRepository extends _i1.Mock implements _i2.IHomeRepository {
  @override
  _i3.Future<_i2.HomeListEntity> getCharacters({
    required int? page,
    String? name,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [],
          {
            #page: page,
            #name: name,
            #status: status,
          },
        ),
        returnValue: _i3.Future<_i2.HomeListEntity>.value(_FakeHomeListEntity_0(
          this,
          Invocation.method(
            #getCharacters,
            [],
            {
              #page: page,
              #name: name,
              #status: status,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.HomeListEntity>.value(_FakeHomeListEntity_0(
          this,
          Invocation.method(
            #getCharacters,
            [],
            {
              #page: page,
              #name: name,
              #status: status,
            },
          ),
        )),
      ) as _i3.Future<_i2.HomeListEntity>);

  @override
  _i3.Future<_i2.HomeCharacterEntity> getCharacterById({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterById,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<_i2.HomeCharacterEntity>.value(
            _FakeHomeCharacterEntity_1(
          this,
          Invocation.method(
            #getCharacterById,
            [],
            {#id: id},
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i2.HomeCharacterEntity>.value(
            _FakeHomeCharacterEntity_1(
          this,
          Invocation.method(
            #getCharacterById,
            [],
            {#id: id},
          ),
        )),
      ) as _i3.Future<_i2.HomeCharacterEntity>);
}

/// A class which mocks [HomeCharacterEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeCharacterEntity extends _i1.Mock
    implements _i2.HomeCharacterEntity {
  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#status),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#status),
        ),
      ) as String);

  @override
  String get species => (super.noSuchMethod(
        Invocation.getter(#species),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#species),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#species),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  String get gender => (super.noSuchMethod(
        Invocation.getter(#gender),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#gender),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#gender),
        ),
      ) as String);

  @override
  String get originName => (super.noSuchMethod(
        Invocation.getter(#originName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#originName),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#originName),
        ),
      ) as String);

  @override
  String get originUrl => (super.noSuchMethod(
        Invocation.getter(#originUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#originUrl),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#originUrl),
        ),
      ) as String);

  @override
  String get locationName => (super.noSuchMethod(
        Invocation.getter(#locationName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#locationName),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#locationName),
        ),
      ) as String);

  @override
  String get locationUrl => (super.noSuchMethod(
        Invocation.getter(#locationUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#locationUrl),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#locationUrl),
        ),
      ) as String);

  @override
  String get image => (super.noSuchMethod(
        Invocation.getter(#image),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#image),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#image),
        ),
      ) as String);

  @override
  List<String> get episode => (super.noSuchMethod(
        Invocation.getter(#episode),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);
}
