// Mocks generated by Mockito 5.4.4 from annotations
// in rick_morty/test/app/domain_layer/use_cases/get_home_characters_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_morty/app/domain_layer/domain_layer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeListEntity_0 extends _i1.SmartFake
    implements _i2.HomeListEntity {
  _FakeHomeListEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeCharacterEntity_1 extends _i1.SmartFake
    implements _i2.HomeCharacterEntity {
  _FakeHomeCharacterEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeInfoEntity_2 extends _i1.SmartFake
    implements _i2.HomeInfoEntity {
  _FakeHomeInfoEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IHomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHomeRepository extends _i1.Mock implements _i2.IHomeRepository {
  @override
  _i3.Future<_i2.HomeListEntity> getCharacters({
    required int? page,
    String? name,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [],
          {
            #page: page,
            #name: name,
            #status: status,
          },
        ),
        returnValue: _i3.Future<_i2.HomeListEntity>.value(_FakeHomeListEntity_0(
          this,
          Invocation.method(
            #getCharacters,
            [],
            {
              #page: page,
              #name: name,
              #status: status,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.HomeListEntity>.value(_FakeHomeListEntity_0(
          this,
          Invocation.method(
            #getCharacters,
            [],
            {
              #page: page,
              #name: name,
              #status: status,
            },
          ),
        )),
      ) as _i3.Future<_i2.HomeListEntity>);

  @override
  _i3.Future<_i2.HomeCharacterEntity> getCharacterById({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterById,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<_i2.HomeCharacterEntity>.value(
            _FakeHomeCharacterEntity_1(
          this,
          Invocation.method(
            #getCharacterById,
            [],
            {#id: id},
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i2.HomeCharacterEntity>.value(
            _FakeHomeCharacterEntity_1(
          this,
          Invocation.method(
            #getCharacterById,
            [],
            {#id: id},
          ),
        )),
      ) as _i3.Future<_i2.HomeCharacterEntity>);
}

/// A class which mocks [HomeListEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeListEntity extends _i1.Mock implements _i2.HomeListEntity {
  @override
  _i2.HomeInfoEntity get info => (super.noSuchMethod(
        Invocation.getter(#info),
        returnValue: _FakeHomeInfoEntity_2(
          this,
          Invocation.getter(#info),
        ),
        returnValueForMissingStub: _FakeHomeInfoEntity_2(
          this,
          Invocation.getter(#info),
        ),
      ) as _i2.HomeInfoEntity);

  @override
  List<_i2.HomeCharacterEntity> get results => (super.noSuchMethod(
        Invocation.getter(#results),
        returnValue: <_i2.HomeCharacterEntity>[],
        returnValueForMissingStub: <_i2.HomeCharacterEntity>[],
      ) as List<_i2.HomeCharacterEntity>);
}
